#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/Config/secrets.local.env"
OUTPUT_DIR="$ROOT/gumimap-v2/Generated"
OUTPUT_FILE="$OUTPUT_DIR/Secrets.generated.swift"

mkdir -p "$OUTPUT_DIR"

read_env() {
  local key="$1"
  local default="${2:-}"
  if [[ -f "$ENV_FILE" ]]; then
    local value
    value="$(grep -E "^${key}=" "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
    if [[ -n "$value" ]]; then
      printf '%s' "$value"
      return
    fi
  fi
  printf '%s' "$default"
}

escape_swift_string() {
  python3 -c 'import sys; print(sys.stdin.read().replace("\\", "\\\\").replace("\"", "\\\""), end="")'
}

KAKAO_REST_API_KEY="$(read_env KAKAO_REST_API_KEY)"
KAKAO_NATIVE_APP_KEY="$(read_env KAKAO_NATIVE_APP_KEY)"

KAKAO_REST_API_KEY_ESCAPED="$(printf '%s' "$KAKAO_REST_API_KEY" | escape_swift_string)"
KAKAO_NATIVE_APP_KEY_ESCAPED="$(printf '%s' "$KAKAO_NATIVE_APP_KEY" | escape_swift_string)"

cat > "$OUTPUT_FILE" <<EOF
// Generated by scripts/generate-secrets.sh — do not edit.
import Foundation

enum GeneratedSecrets {
    static let kakaoRestAPIKey = "$KAKAO_REST_API_KEY_ESCAPED"
    static let kakaoNativeAppKey = "$KAKAO_NATIVE_APP_KEY_ESCAPED"
}
EOF